// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chat(arg1:string,arg2:Array<Record<string, string>>):Promise<string>;

export function CheckStatus():Promise<main.StatusResult>;

export function DeleteInstalledModel(arg1:string):Promise<void>;

export function ExportEmbeddings(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function ExportTextGen(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function GetAvailableDevices():Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function GetInstalledModels():Promise<Array<main.ModelInfo>>;

export function GetPipelineFilters():Promise<Array<string>>;

export function GetStartupEnabled():Promise<boolean>;

export function IsOVMSRunning():Promise<boolean>;

export function PrepareOVMS():Promise<void>;

export function PullModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetModels():Promise<void>;

export function ResetOVMS():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SearchModels(arg1:string,arg2:Array<string>):Promise<Array<main.HFModel>>;

export function SetStartup(arg1:boolean):Promise<void>;

export function StartOVMS():Promise<void>;

export function StopOVMS():Promise<void>;
