// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function PrepareExport() {
  return window['go']['main']['App']['PrepareExport']();
}

export function PrepareOVMS() {
  return window['go']['main']['App']['PrepareOVMS']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
