// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckStatus() {
  return window['go']['main']['App']['CheckStatus']();
}

export function DeleteInstalledModel(arg1) {
  return window['go']['main']['App']['DeleteInstalledModel'](arg1);
}

export function ExportEmbeddings(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportEmbeddings'](arg1, arg2, arg3);
}

export function ExportTextGen(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportTextGen'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstalledModels() {
  return window['go']['main']['App']['GetInstalledModels']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function IsOVMSRunning() {
  return window['go']['main']['App']['IsOVMSRunning']();
}

export function PrepareOVMS() {
  return window['go']['main']['App']['PrepareOVMS']();
}

export function PullModel(arg1, arg2) {
  return window['go']['main']['App']['PullModel'](arg1, arg2);
}

export function ResetExport() {
  return window['go']['main']['App']['ResetExport']();
}

export function ResetOVMS() {
  return window['go']['main']['App']['ResetOVMS']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchModels(arg1, arg2) {
  return window['go']['main']['App']['SearchModels'](arg1, arg2);
}

export function SetStartup(arg1) {
  return window['go']['main']['App']['SetStartup'](arg1);
}

export function StartOVMS() {
  return window['go']['main']['App']['StartOVMS']();
}

export function StopOVMS() {
  return window['go']['main']['App']['StopOVMS']();
}
